version: '3.2'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - postgres
    image: operative-nginx
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    image: operative-php-fpm
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: operative
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
